import { AlertTriangle, CheckCircle2 } from 'lucide-react'
import Button from './Button'

function QualityAssessment({ qualityScore = 86, qualityStatus = 'Good', qualityIssues = ['Minor garment edge distortion', 'Slight shadow variation'], onTryAgain = () => { window.location.href = '/upload' } }) {
  const isGood = qualityStatus === 'Good'

  return <section className="mt-10 rounded-md border border-line bg-surface p-5 sm:p-7" aria-labelledby="quality-assessment-heading"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-accent">Automated review</p><h2 id="quality-assessment-heading" className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-ink">Quality Assessment</h2><p className="mt-2 text-sm leading-6 text-muted">A preliminary check of this virtual try-on result.</p></div><div className={`inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold ${isGood ? 'bg-[#f3faf5] text-success' : 'bg-[#fff5e8] text-[#9a6415]'}`}><span className="text-2xl font-semibold leading-none">{qualityScore}</span><span className="text-xs font-bold uppercase tracking-[0.1em]">/ 100</span></div></div><div className="mt-6 flex flex-wrap items-center gap-3"><span className={`inline-flex items-center gap-2 text-sm font-semibold ${isGood ? 'text-success' : 'text-[#9a6415]'}`}>{isGood ? <CheckCircle2 size={17} aria-hidden="true" /> : <AlertTriangle size={17} aria-hidden="true" />} {qualityStatus}</span><div className="h-2 min-w-48 flex-1 overflow-hidden rounded-full bg-accent-soft" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow={qualityScore} aria-label={`Quality score: ${qualityScore} out of 100`}><div className="h-full rounded-full bg-accent" style={{ width: `${qualityScore}%` }} /></div></div>{!isGood ? <div className="mt-5 rounded-md border border-[#f0d5a9] bg-[#fffaf2] p-4"><p className="text-sm font-semibold text-ink">Please try a clearer photo and try again</p>{onTryAgain ? <Button size="sm" variant="outline" className="mt-3" onClick={onTryAgain}>Try Again</Button> : null}</div> : null}<div className="mt-6 border-t border-line pt-5"><h3 className="text-sm font-semibold text-ink">Detected issues</h3>{qualityIssues.length ? <ul className="mt-3 grid gap-2 sm:grid-cols-2">{qualityIssues.map((issue) => <li key={issue} className="flex items-start gap-2 text-sm text-muted"><AlertTriangle size={15} className="mt-0.5 shrink-0 text-[#b8893f]" aria-hidden="true" />{issue}</li>)}</ul> : <p className="mt-3 text-sm text-muted">No issues detected.</p>}</div></section>
}

export default QualityAssessment